# Generated by Django 5.0.4 on 2026-04-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Turnir nomi')),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('format', models.CharField(choices=[('league', 'Liga (barcha barchaga qarshi)'), ('knockout', "Playoff (to'g'ridan-to'g'ri)"), ('group_knockout', 'Guruh + Playoff')], default='league', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Tayyorlanmoqda'), ('registration', "Ro'yxatga olish"), ('ongoing', 'Davom etmoqda'), ('finished', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20)),
                ('max_teams', models.PositiveIntegerField(default=8)),
                ('min_players_per_team', models.PositiveIntegerField(default=5)),
                ('max_players_per_team', models.PositiveIntegerField(default=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('prize_info', models.TextField(blank=True, null=True, verbose_name='Sovrin haqida')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Qoidalar')),
                ('win_points', models.PositiveIntegerField(default=3)),
                ('draw_points', models.PositiveIntegerField(default=1)),
                ('loss_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, help_text='Turnirni boshqara oladigan adminlar', related_name='administered_tournaments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turnir',
                'verbose_name_plural': 'Turnirlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A guruh, B guruh va h.k.', max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='tournaments.tournamentgroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': "Ro'yxat",
                'verbose_name_plural': "Ro'yxatlar",
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
