# Generated by Django 6.1 on 2026-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='require_match_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
