# Generated by Django 6.1 on 2026-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamlineup_teamlineupslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='squad_size',
            field=models.PositiveSmallIntegerField(choices=[(5, '5x5'), (7, '7x7'), (11, '11x11')], default=11),
        ),
        migrations.AlterField(
            model_name='teamlineup',
            name='formation',
            field=models.CharField(choices=[('1-2-1', '1-2-1'), ('2-1-1', '2-1-1'), ('2-2', '2-2'), ('2-3-1', '2-3-1'), ('3-1-2', '3-1-2'), ('3-2-1', '3-2-1'), ('3-5-2', '3-5-2'), ('4-2-3-1', '4-2-3-1'), ('4-3-3', '4-3-3'), ('4-4-2', '4-4-2')], default='4-4-2', max_length=10),
        ),
    ]
