# Generated by Django 5.0.4 on 2026-04-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Guruh bosqichi'), ('round_of_16', '1/8 final'), ('quarter_final', 'Chorak final'), ('semi_final', 'Yarim final'), ('third_place', "Uchinchi o'rin"), ('final', 'Final'), ('league', 'Liga')], default='league', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('live', 'Jonli'), ('finished', 'Tugallangan'), ('postponed', 'Kechiktirilgan'), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20)),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.tournamentgroup')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('match_admin', models.ForeignKey(blank=True, help_text="Bu o'yinda statistika kiritadigan admin", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_matches', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Gol'), ('assist', 'Assist'), ('yellow_card', 'Sariq karta'), ('red_card', 'Qizil karta'), ('substitution_in', 'Almashtirildi (kirdi)'), ('substitution_out', 'Almashtirildi (chiqdi)'), ('own_goal', "O'z darvozasiga gol")], max_length=20)),
                ('minute', models.PositiveIntegerField(help_text="O'yin daqiqasi")),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='teams.team')),
            ],
            options={
                'verbose_name': "O'yin voqeasi",
                'verbose_name_plural': "O'yin voqealari",
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('is_starting', models.BooleanField(default=True, help_text='Asosiy tarkibdami?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='teams.team')),
            ],
            options={
                'verbose_name': "O'yinchi statistikasi",
                'verbose_name_plural': "O'yinchi statistikalari",
                'unique_together': {('match', 'player')},
            },
        ),
    ]
